import type { PokemonTypeName } from "@/types/pokemonTypes";
import { StyleSheet } from "react-native";

export type { PokemonTypeName };

// Solid colors for type-themed cards (if you want to swap from yellow later).
export const typeCardColors: Record<PokemonTypeName, string> = {
	normal: "#A8A77A",
	fire: "#EE8130",
	water: "#6390F0",
	electric: "#F7D02C",
	grass: "#7AC74C",
	ice: "#96D9D6",
	fighting: "#C22E28",
	poison: "#A33EA1",
	ground: "#E2BF65",
	flying: "#A98FF3",
	psychic: "#F95587",
	bug: "#A6B91A",
	rock: "#B6A136",
	ghost: "#735797",
	dragon: "#6F35FC",
	dark: "#705746",
	steel: "#B7B7CE",
	fairy: "#D685AD",
};

// Lower-half gradients for each type (transparent -> tinted).
// NOTE: LinearGradient "colors" are not StyleSheet styles, so we export config.
export const typeLowerHalfGradients: Record<PokemonTypeName, { colors: [string, string] }> = {
	normal: { colors: ["transparent", "rgba(168,167,122,1)"] },
	fire: { colors: ["transparent", "rgba(238,129,48,1)"] },
	water: { colors: ["transparent", "rgba(99,144,240,1)"] },
	electric: { colors: ["transparent", "rgba(247,208,44,1)"] },
	grass: { colors: ["transparent", "rgba(122,199,76,1)"] },
	ice: { colors: ["transparent", "rgba(150,217,214,1)"] },
	fighting: { colors: ["transparent", "rgba(194,46,40,1)"] },
	poison: { colors: ["transparent", "rgba(163,62,161,1)"] },
	ground: { colors: ["transparent", "rgba(226,191,101,1)"] },
	flying: { colors: ["transparent", "rgba(169,143,243,1)"] },
	psychic: { colors: ["transparent", "rgba(249,85,135,1)"] },
	bug: { colors: ["transparent", "rgba(166,185,26,1)"] },
	rock: { colors: ["transparent", "rgba(182,161,54,1)"] },
	ghost: { colors: ["transparent", "rgba(115,87,151,1)"] },
	dragon: { colors: ["transparent", "rgba(111,53,252,1)"] },
	dark: { colors: ["transparent", "rgba(112,87,70,1)"] },
	steel: { colors: ["transparent", "rgba(183,183,206,1)"] },
	fairy: { colors: ["transparent", "rgba(214,133,173,1)"] },
};

const styles = StyleSheet.create({
	screen: {
		flex: 1,
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: "#1b2735",
		padding: 16,
	},
	card: {
		width: 300,
		aspectRatio: 2.5 / 3.5,
		borderRadius: 12,
		backgroundColor: "#f7e35c",
		borderWidth: 9,
		borderColor: "#8b8b8b",
		padding: 10,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 4 },
		shadowOpacity: 0.3,
		shadowRadius: 8,
		elevation: 6,
		overflow: "hidden",
	},
	cardWater: {
		backgroundColor: "#52c3f0"
	},
	cardNormal: { backgroundColor: typeCardColors.normal },
	cardFire: { backgroundColor: typeCardColors.fire },
	cardElectric: { backgroundColor: typeCardColors.electric },
	cardGrass: { backgroundColor: typeCardColors.grass },
	cardIce: { backgroundColor: typeCardColors.ice },
	cardFighting: { backgroundColor: typeCardColors.fighting },
	cardPoison: { backgroundColor: typeCardColors.poison },
	cardGround: { backgroundColor: typeCardColors.ground },
	cardFlying: { backgroundColor: typeCardColors.flying },
	cardPsychic: { backgroundColor: typeCardColors.psychic },
	cardBug: { backgroundColor: typeCardColors.bug },
	cardRock: { backgroundColor: typeCardColors.rock },
	cardGhost: { backgroundColor: typeCardColors.ghost },
	cardDragon: { backgroundColor: typeCardColors.dragon },
	cardDark: { backgroundColor: typeCardColors.dark },
	cardSteel: { backgroundColor: typeCardColors.steel },
	cardFairy: { backgroundColor: typeCardColors.fairy },
	lowerHalfGradient: {
		position: "absolute",
		left: 0,
		right: 0,
		bottom: 0,
		height: "100%",
	},
	nameRow: {
		flexDirection: "row",
		alignItems: "center",
		gap: 8,
		paddingVertical: 6,
		paddingHorizontal: 4,
		borderBottomWidth: 1,
		borderBottomColor: "rgba(0,0,0,0.08)",
	},
	nameInput: {
		backgroundColor: "rgba(255,255,255,0.85)",
		borderWidth: 1.5,
		borderColor: "#9ca3af",
		borderRadius: 6,
		fontSize: 15,
		fontWeight: "bold",
		color: "#1f2937",
		paddingVertical: 4,
		paddingHorizontal: 6,
		flex: 1,
		flexShrink: 1,
		minWidth: 0,
	},
	/** Read-only “input” look when the answer is revealed after guessing. */
	nameRevealCorrect: {
		backgroundColor: "rgba(240, 253, 244, 0.95)",
		borderColor: "#22c55e",
		color: "#14532d",
	},
	nameRevealWrong: {
		backgroundColor: "rgba(254, 242, 242, 0.95)",
		borderColor: "#f87171",
		color: "#7f1d1d",
	},
	typeIconsRow: {
		flexDirection: "row",
		alignItems: "center",
		gap: 6,
		flexShrink: 0,
	},
	imageWrapper: {
		height: 168,
		backgroundColor: "#fdf8e4",
		borderRadius: 8,
		borderWidth: 2,
		borderColor: "#8b8b8b",
		overflow: "hidden",
		alignItems: "center",
		justifyContent: "center",
		marginVertical: 6,
	},
	image: {
		width: "100%",
		height: "100%",
		resizeMode: "contain",
	},
	attackRow: {
		paddingVertical: 10,
		paddingHorizontal: 6,
		borderTopWidth: 1,
		borderTopColor: "rgba(0,0,0,0.08)",
	},
	hintRow: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		paddingVertical: 4,
		paddingHorizontal: 6,
		backgroundColor: "rgba(255,255,255,0.6)",
		borderRadius: 8,
		borderWidth: 1,
		borderColor: "rgba(0,0,0,0.12)",
		marginBottom: 8,
	},
	hintLabel: {
		color: "#374151",
		fontSize: 14,
		fontWeight: "700",
		letterSpacing: 0.4,
		textTransform: "uppercase",
		marginRight: 10,
	},
	hintValue: {
		color: "#111827",
		fontSize: 14,
		fontWeight: "600",
		flexShrink: 1,
		textAlign: "right",
	},
	hintButton: {
		backgroundColor: "#ca793b",
		paddingVertical: 4,
		paddingHorizontal: 20,
		borderRadius: 8,
		alignItems: "center",
		justifyContent: "center",
		marginBottom: 8,
	},
	hintButtonText: {
		color: "#ffffff",
		fontWeight: "bold",
		fontSize: 12,
	},
	guessButton: {
		backgroundColor: "#3b4cca",
		paddingVertical: 12,
		paddingHorizontal: 20,
		borderRadius: 8,
		alignItems: "center",
		justifyContent: "center",
	},
	guessButtonText: {
		color: "#ffffff",
		fontWeight: "bold",
		fontSize: 16,
	},
	outcomeBlock: {
		width: 300,
		maxWidth: "100%",
		marginTop: 20,
		paddingVertical: 14,
		paddingHorizontal: 16,
		borderRadius: 12,
		backgroundColor: "rgba(15, 23, 42, 0.72)",
		borderWidth: 1,
		borderColor: "rgba(148, 163, 184, 0.35)",
	},
	outcomeGuessRow: {
		marginBottom: 10,
	},
	outcomeLabel: {
		fontSize: 11,
		fontWeight: "700",
		letterSpacing: 1.2,
		textTransform: "uppercase",
		color: "#94a3b8",
		marginBottom: 4,
	},
	outcomeGuessText: {
		fontSize: 17,
		fontWeight: "700",
		color: "#f8fafc",
		letterSpacing: 0.3,
	},
	outcomeVerdict: {
		fontSize: 15,
		fontWeight: "800",
		letterSpacing: 0.5,
	},
	outcomeVerdictCorrect: {
		color: "#4ade80",
		textShadowColor: "rgba(74, 222, 128, 0.45)",
		textShadowOffset: { width: 0, height: 0 },
		textShadowRadius: 12,
	},
	outcomeVerdictWrong: {
		color: "#fb7185",
		textShadowColor: "rgba(251, 113, 133, 0.4)",
		textShadowOffset: { width: 0, height: 0 },
		textShadowRadius: 10,
	},
});

export default styles;